---
apiVersion: v1
kind: Service
metadata:
  name: gol-dev
spec:
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 32765
  selector:  
    app: gol
    env: dev
  type: NodePort
    
     