---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-qa
spec:
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 32766
  selector:  
    app: jenkins
    env: qa
  type: NodePort
    