---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins
spec:
  minReadySeconds: 30
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
      env: qa
  template:
    metadata:
      labels: 
        app: jenkins
        env: qa
    spec:
      containers:
        - image: jenkins:2.60.3
          name: jenkins-cont
          ports:
            - containerPort: 8080
              name: jnk-port
            

