---
apiVersion: v1
kind: Pod
metadata:
  name: gameoflife
spec:
  containers: 
    - image: saieswarprasad/gameoflife:v1
      name: gol
      resources: 
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"  
      ports:
        - containerPort: 8080
          name: golhttpport
          protocol: TCP
      image: httpd
      name: httpd
      ports:
        - containerPort: 80
          name: httpdport