---
apiVersion: v1
kind: Pod
metadata:
  name: gameoflife
spec:
  containers: 
    - image: saieswarprasad/gameoflife:v1
      name: gol
      ports:
        - containerPort: 8080
          name: golhttpport
          protocol: TCP